Accounts/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'Accounts'

urlpatterns = [
    path('login/',   auth_views.LoginView.as_view(template_name='registration/login.html'), name="login"),
    path('register/',  views.registration_form, name="register"),
    path('profile/',  views.profile, name="profile"),
]

Info/urls.py
from django.conf.urls import url

from django.urls import path
from . import views


app_name = 'Info'

urlpatterns = [
    path('', views.home, name='home'),
    # url(r'home', views.home, name="home"),
]

ntech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import path

urlpatterns = [
   # url(r'^config/', admin.site.urls),
    path('config/', admin.site.urls),
    path('info/', include('Info.urls')),
    path('accounts/',include('Accounts.urls')),
    # url(r'^info/', include('Info.urls')),
   #  url(r'^accounts/', include('Accounts.urls')),
]

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    SKIll_LEVEL = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Expert', 'Expert'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        
    )

    COUNTRY = (
        ('Kenya', 'Kenya'),
        ('Rwanda', 'Rwanda'),
      ('Uganda', 'Uganda'),
        
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=50,null=True)
    gender =  models.CharField(max_length=20,choices=GENDER,null=True)
    assessor = models.BooleanField(default=False)
    country = models.CharField(max_length=20,choices=COUNTRY,null=True)
    language = models.TextField(max_length=500, blank=False)
    skill_level = models.CharField(max_length=20, choices=SKIll_LEVEL)
    institution = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.username


# Hooking the following methods to the Django defined User model
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

Info/models.py
from django.db import models as md


class Institution(md.Model):
    name = md.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "institution"

Accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile
class SignUpForm(UserCreationForm):
    SKIll_LEVEL = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Expert', 'Expert'),
    )

    COUNTRY = (
        ('Kenya', 'Kenya'),
        ('Rwanda', 'Rwanda'),
      ('Uganda', 'Uganda'),
        
    )


    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        
    )

    language = forms.CharField(max_length=100)
    skill_level = forms.ChoiceField(choices=SKIll_LEVEL,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)

    institution = forms.CharField(max_length=50)

    gender =  forms.ChoiceField(choices=GENDER,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)
                                    
    country =  forms.ChoiceField(choices=COUNTRY,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)

    phone_number = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'institution','phone_number','gender','country', 'language',
                  'skill_level')
        help_texts = {
            'username': None,
            'email': None,
            'password1': None,
            'password2': None,
        }
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)


        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(
                Submit('login', 'Login', css_class='blue-btn')
            )
        )


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email',]


class ProfileUpdateForm(forms.ModelForm):

    SKIll_LEVEL = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Expert', 'Expert'),
    )

    COUNTRY = (
        ('Kenya', 'Kenya'),
        ('Rwanda', 'Rwanda'),
      ('Uganda', 'Uganda'),
        
    )


    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        
    )
    skill_level = forms.ChoiceField(choices=SKIll_LEVEL,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)

    gender =  forms.ChoiceField(choices=GENDER,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)
                                    
    country =  forms.ChoiceField(choices=COUNTRY,
                                    label="",
                                    initial='',
                                    widget=forms.Select(),
                                    required=True)

    class Meta:
        model = Profile
        fields = ['institution','skill_level','language','gender','country']

Info/forms.py
from django.forms import ModelForm

from .models import Institution


class InstitutionCreation(ModelForm):
    class Meta:
        model = Institution
        fields = ("name",)

Accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import SignUpForm
from .forms import UserUpdateForm, ProfileUpdateForm


def registration_form(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # hard refresh load the profile instance created by the signal
            user.profile.language = form.cleaned_data.get('language')
            user.profile.phone_number = form.cleaned_data.get('phone_number')
            user.profile.skill_level = form.cleaned_data.get('skill_level')
            user.profile.institution = form.cleaned_data.get('institution')
            user.profile.gender = form.cleaned_data.get('gender')
            user.profile.country = form.cleaned_data.get('country')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('Info:home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


@login_required  # the user must be logged in
def profile(request):

    if request.method == 'POST':
        u_form = SignUpForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user)
       
        if u_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been Updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user)
        

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'profile.html', context)

Info/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html', {})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Technologists Hacks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {% block styles %}{% endblock %}
    <link rel="shortcut icon" type="image/png" href={% static "images/favicon.png" %}>
    <link rel="stylesheet" href={% static "css/base.css" %}/>
    <link rel="stylesheet" href={% static "css/ionicons.css" %}/>
    <script type="text/javascript" src={% static "js/jquery-3.3.1.min.js" %}></script>
    <script src={% static "js/util.js" %}></script>
</head>
<body>
<div class="header ruled">
    {% block header %}
        {% comment "Menu and other header content go here" %}{% endcomment %}
    {% endblock %}
</div>
<div class="content">
    {% block content %}
        {% comment "the main content of the extending template go here" %}{% endcomment %}
    {% endblock %}
</div>
<script src={% static "js/util.js" %}></script>
<script src={% static "js/waypoints.js" %}></script>
<script>
    shadow_on_scroll(".header", ".content");
</script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/home.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem active"><a href="#">Home</a></li>
            <li class="menuitem"><a href="#">Schedule</a></li>
            <li class="menuitem"><a href="#">FAQ</a></li>
            <li class="menuitem"><a href="#">About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        <a class="medium-description blue" href="{% url 'Accounts:login'  %}"><i class="ion-ios-person"></i>&nbsp;Sign in</a>
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    <div class="overlay hidden">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled">
            <ul role="menubar">
                <li class="menuitem-v active"><a href="#"><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href="#"><i class="ion-ios-stopwatch blue"></i>Schedule</a></li>
                <li class="menuitem-v"><a href="#"><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href="#"><img width="20px" height="20px" alt="ntect-logo"
                                                        src={% static "images/favicon.png" %}>&nbsp;About</a></li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">

                {%if user.is_authenticated %}
                {% else %}
                <li class="menuitem-v blue"><a href="{% url 'Accounts:register' %}"><i class="ion-ios-person"></i>Register</a>
                </li>
                <li class="menuitem-v blue"><a href="{% url 'Accounts:login' %}"><i class="ion-log-in blue"></i>Sign in</a></li>
                {% endif %}
  
           
           
           
            </ul>
        </div>
    </div>
    <div id="main-desc" class="container medium-description waypoint">
        <img id="logo-img" class="left img" src={% static "images/ntech.png" %}/>
        <div id="main-desc-text" class="medium-description">
            <p class="large-description container">Ntech Hackathon 2019</p>
            <strong>N-Tech</strong> (<i>New Technologists & Innovators</i>) is a youth-led initiative that aims to
            empower youth to drive technological advancements as the fourth Industrial Revolution unveils. Young
            people today are going to be the leaders of tomorrow. But, is it not mismatching that one third of the,
            rapidly accelerating, youth population in Africa is unemployed today?<br>
            N-Tech hackathon is an annual event and we are currently seeking
            Participants (undergraduate or graduate university students) and sponsors for this year's event. They will
            team-up
            depending on topics that they are mutually interested in, work together for 30 hours to develop a solution
            to the prompt. Thereafter, submissions will be evaluated by a panel of judges and the selected finalists
            will pitch their ideas to the organizations. Top teams will then be selected.
        </div>
    </div>
    <div class="container ruled waypoint" style="height: 40px; margin-top: 20px;padding-bottom: 20px">
        <a href= "#">
            <button class="blue-btn center" style="width: 120px;">Register</button>
        </a>
        <a href="#">
            <button class="blue-btn center" style="width: 120px;">Read more</button>
        </a>
    </div>
    <p class="large-description blue waypoint">Currently involving three countries</p>
    <p class="container blockquote waypoint-side" style="max-width: 800px">
        This year, 2019, it will concurrently be hosted in Kenya, Rwanda, and Uganda (we hope to expand in the future).
        Each country will have a theme
        that relates to some of the major issues but still contributes to our overall mission, empowering youth to
        take the lead in the fourth industrial revolution.
    </p>
    <div class="container">
        <img id="map-img" class="wide-img center waypoint" alt="countries-kenya-uganda-rwanda"
             src={% static "images/map.png" %}/>
    </div>
    <div id="commentaries" class="ruled">
        <div class="commentary waypoint-side" style="background: rgba(225, 77, 17, 0.28)">
            <img class="comm-prof-img" src={% static "images/rwanda.jpg" %}/>
            <p class="small-description comm-text"> {% lorem 30 w random %}</p>
            <p class="commentor right">~ Resire, Rwanda</p>
        </div>
        <div class="commentary waypoint-side" style="background: rgba(113, 197, 241, 0.24)">
            <img class="comm-prof-img" src={% static "images/uganda.jpg" %}/>
            <p class="small-description comm-text"> {% lorem 30 w random %}</p>
            <p class="commentor right">~ Silas, Uganda</p>
        </div>
        <div class="commentary waypoint-side terminate" style="background: rgba(171, 141, 193, 0.28);">
            <img class="comm-prof-img" src={% static "images/kenya.jpg" %}/>
            <p class="small-description comm-text"> {% lorem 30 w random %}</p>
            <p class="commentor right">~ Ronald, Kenya</p>
        </div>
    </div>
    <p class="large-description container waypoint" id="social-intro" style="margin-top: 40px;">Know more about us</p>
    <p class="small-description container waypoint" style=";max-width: 600px; margin: 0 auto">Follow, Add and and friend
        us on all popular platforms
        and get to experience the great things we do. Find our groundbreaking creations on github. We really hope you
        can
        add to our vast collection.</p>
    <div class="container" id="social">
        <div class="social-link waypoint-side">
            <a href="#">
                <i class="ion-social-instagram"></i>
                <span>Instagram</span>
            </a>
        </div>
        <div class="social-link waypoint-side">
            <i class="ion-social-facebook"></i>
            <span>Facebook</span>
        </div>
        <div class="social-link waypoint-side">
            <i class="ion-social-twitter"></i>
            <span>Twitter</span>
        </div>
        <div class="social-link waypoint-side terminate">
            <i class="ion-social-github"></i>
            <span>Github</span>
        </div>
    </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/forms.css" %}>
{% endblock %}
{% block content %}
    <p class=" container medium-description waypoint" style="color: #3d8aff">Update Your Profile</p>





  <form method="post">
    {% csrf_token %}



          <div class="input-layer waypoint-side">
           {{ u_form.username }}
              <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>


            <div class="input-layer waypoint-side">
           {{ u_form.email }}
              <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>

              <div class="container" style="margin:60px 0 60px 0">
    <button type="submit" class="blue-btn">Update </button>
             </div>



  </form> <script src={% static "js/validators.js" %}></script>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/forms.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem"><a href="{% url 'Info:home' %}">Home</a></li>
            <li class="menuitem"><a href="#">Schedule</a></li>
            <li class="menuitem"><a href="#">FAQ</a></li>
            <li class="menuitem"><a href="#">About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        <a class="medium-description blue"><i class="ion-ios-person"></i>&nbsp;Sign in</a>
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    <div class="overlay hidden">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled">
            <ul role="menubar">
                <li class="menuitem-v"><a href={% url "info:home" %}><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href="#"><i class="ion-ios-stopwatch blue"></i>Schedule</a></li>
                <li class="menuitem-v"><a href="#"><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href="#"><img width="20px" height="20px" alt="ntect-logo"
                                                        src={% static "images/favicon.png" %}>&nbsp;About</a></li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
                <li class="menuitem-v blue"><a href="#"><i class="ion-log-in blue"></i>Sign in</a></li>
            </ul>
        </div>
    </div>
    <p class="large-description container waypoint">Ntech Hackathon registration 2019</p>
    <p class="medium-description container waypoint center-text">
        The details below are required for individual registrations. If you wish to enter the hackathon <br>
        as a team, each team member should complete the individual registration<br>
        before proceeding to team registration
    </p>
    <div class="container waypoint" style="height: 40px; margin-top: 20px;padding-bottom: 20px">
        <a href="#">
            <button class="blue-btn center" style="width: 180px;margin: 10px auto">Team registration</button>
        </a>
    </div>
    <hr style="width: 80%;margin: 15px auto 10px" class="waypoint"/>
    <p class=" container medium-description waypoint" style="color: #3d8aff">Individual registration</p>
    <form autocomplete="off" spellcheck="false">
        <div class="container small-description blue waypoint">Contact information</div>
        <div class="input-layer waypoint-side">
            <span class="placeholder">Email</span>
            <input id="email" type="text" name="email" class="data" title="email"/><br>
            <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>
        <div class="input-layer waypoint-side">
            <span class="placeholder">Confirm Email</span>
            <input id="email2" type="text" name="email2" class="data" title="confirm email"/><br>
            <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>
        <div class="input-layer waypoint-side">
            <span class="placeholder">Full name</span>
            <input id="name" type="text" class="data" name="name" title="name"/><br>
            <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>
        <div class="container limit-width ruled">
            <span class="placeholder" style="margin-bottom: 15px;height: 30px;">Mobile contact</span>
            <div class="input-layer select-layer" tabindex="0">
                <input class="value-point" type="text" hidden/>
                <div class="select-val">+<span>254</span> &nbsp;<i class="ion-chevron-down"></i></div>
                <input class="block-input" placeholder="example 712345678" type="number">
                <div class="select">
                    <span class="option">254</span>
                    <span class="option">250</span>
                    <span class="option">256</span>
                </div>
            </div>
        </div>
        <div class="input-layer waypoint-side">
            <span class="placeholder">username</span>
            <input id="username" type="text" name="username" class="data" title="alias"/><br>
            <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>


        
        <div class="container limit-width waypoint" style="display: block">
            <p class="container small-description">
                security information. Use a strong alphanumeric password preferably above 90%
            </p>
            <span id="strength-lbl" class="small-description" style="width:30%">Strength</span>
            <div id="strength">
                <div id="strength-bar"></div>
            </div>
            <span id="strength-val" class="small-description">0 %</span>
        </div>
        <div class="input-layer waypoint-side">
            <span class="placeholder">Password</span>
            <input id="password" type="password" class="data" name="password" title="password"/><br>
            <div class="flash left"></div>
            <div class="flash right"></div>
            <div class="flash-inactive"></div>
        </div>
        <div class="input-layer waypoint-side terminate">
            <span class="placeholder">Confirm Password</span>
            <input id="password2" type="password" class="data" name="password2" title=" confirm password"/><br>
            <div class="flash"></div>
            <div class="flash-inactive"></div>
        </div>
        <p class=" container medium-description waypoint" style="color: #3d8aff">Classification information</p>
        <div class="container limit-width">
            <div class="input-layer select-layer" style="width: 100%" tabindex="0">
                <input class="value-point" id="institution" name="institution" type="text" hidden/>
                <div class="select-val"><span>Select Institution</span> &nbsp;<i class="ion-chevron-down"></i></div>
                <div class="select">
                    <span class="option">&nbsp;Select Institution</span>
                    {% for institution in institutions %}
                        <span class="option">&nbsp;{{ institution }}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
        <p class="container limit-width waypoint small-description">
            If your institution is not available fill in the other section below
        </p>
        <div class="input-layer waypoint-side">
            <span class="placeholder">Other</span>
            <input id="new_institution" type="text" class="data" name="institution"/><br>
            <div class="flash left"></div>
            <div class="flash right"></div>
            <div class="flash-inactive"></div>
        </div>
        <div class="container limit-width" style="height: 60px">
            <div class="input-layer select-layer" style="width:48%;margin-right:1%;margin-left: 1%" tabindex="0">
                <input class="value-point" type="text" hidden/>
                <div class="select-val"><span>Gender</span> &nbsp;<i class="ion-chevron-down"></i></div>
                <div class="select">
                    <span class="option">Male</span>
                    <span class="option">Female</span>
                </div>
            </div>
            <div class="input-layer select-layer" style="width:48%;margin-right:1%;margin-left: 1%" tabindex="0">
                <input class="value-point" type="text" hidden/>
                <div class="select-val"><span>Country</span> &nbsp;<i class="ion-chevron-down"></i></div>
                <div class="select">
                    <span class="option"><img class="flag-img" alt="ke"
                                              src={% static "images/ke.png" %}>&nbsp;Kenya</span>
                    <span class="option"><img class="flag-img" alt="ug"
                                              src={% static "images/ug.png" %}>&nbsp;Uganda</span>
                    <span class="option"><img class="flag-img" alt="rw"
                                              src={% static "images/rw.png" %}>&nbsp;Rwanda</span>
                </div>
            </div>
        </div>
        <div class="container limit-width">
            <div class="input-layer waypoint-side" style="width: 60%">
                <span class="placeholder placeholder-hidden">Date of birth</span>
                <input id="dob" type="date" class="data" name="dob" title="date of birth"/>
                <br>
                <div class="flash left"></div>
                <div class="flash right"></div>
                <div class="flash-inactive"></div>
            </div>
            <p class="small-description container" id="age-val" style="width: 40%;align-items: center">Age:&nbsp;
                <span></span></p>
        </div>
        <div class="container limit-width">
            <div class="input-layer select-layer" style="width: 100%" tabindex="0">
                <input class="value-point" id="skill" name="skill" type="text" hidden/>
                <div class="select-val"><span>Select skill</span> &nbsp;<i class="ion-chevron-down"></i></div>
                <div class="select">
                    <span class="option">&nbsp;Select skill</span>
                    <span class="option">&nbsp;Coding</span>
                    <span class="option">&nbsp;Critical thinking</span>
                    <span class="option">&nbsp;Graphic design</span>
                    <span class="option">&nbsp;Electronics</span>
                    <span class="option">&nbsp;Marketing</span>
                </div>
            </div>
        </div>
        <p class="container limit-width small-description waypoint">
            You can select multiple skills and they will appear below.
        </p>
        <div id="skill-tags" class="container limit-width tag-container waypoint">

        </div>
        <div class="container" style="margin:60px 0 60px 0">
            <button class="blue-btn">Finish registration</button>
        </div>
    </form>
    <script src={% static "js/validators.js" %}></script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load static %}

{% load crispy_forms_tags %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/forms.css" %}>
{% endblock %}
{% block content %}
<p class=" container medium-description waypoint" style="color: #3d8aff">Register</p>


      <form method="post">
    {% csrf_token %}


    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}


        <div class="container" style="margin:60px 0 60px 0">
            <button type="submit" class="blue-btn"> Register</button>
        </div>
  </form>





{% endblock %}